// W21: Agent Zombies detector (daily).
// Scans Linear for issues labeled `claude-task` in a started state (In Progress /
// In Review), older than 4h since startedAt, with NO attachment linking to a
// GitHub PR. That pattern = a background Claude agent claimed the issue, went
// In Progress, and dropped off without shipping. Posts a single rolling
// workspace-wide meta-issue so Henry can reassign or re-spawn the agent.
//
// Signature: [agent-zombies] — singleton (one rolling issue across the whole
// workspace; NOT per-repo, NOT per-issue).
// Dedup: ensureIssue → title startsWith [agent-zombies]. Heartbeat on match;
//        G1 CHECK 2 (>14d no update) will eventually close stale instances.
//        No custom gonePolicy entry in linear-scrub yet — flagged as follow-up.
//
// Cross-repo: no TARGET_REPO. Workflow runs once, not a matrix.

import { ensureIssue, commentOnIssue, listClaudeTaskZombies } from '../lib/linear.mjs';

const MAX_AGE_HOURS = 4;

const { labelExists, zombies } = await listClaudeTaskZombies({ maxAgeHours: MAX_AGE_HOURS });

if (!labelExists) {
  console.log('no claude-task label — skipping');
  process.exit(0);
}

if (zombies.length === 0) {
  console.log('No agent zombies found.');
  process.exit(0);
}

const now = Date.now();
const enriched = zombies.map((z) => {
  const startedAt = z.startedAt ? new Date(z.startedAt).getTime() : new Date(z.updatedAt).getTime();
  const hours = Math.floor((now - startedAt) / 3600000);
  return {
    id: z.id,
    identifier: z.identifier,
    title: z.title,
    url: z.url,
    assignee: z.assignee?.displayName || z.assignee?.name || 'unassigned',
    team: z.team?.key || '?',
    hours,
    startedAt: z.startedAt,
  };
});

enriched.sort((a, b) => b.hours - a.hours);

const signature = '[agent-zombies]';
const pluralS = enriched.length === 1 ? '' : 's';
const title = `${signature} ${enriched.length} claude-task issue${pluralS} stalled >${MAX_AGE_HOURS}h with no PR`;

const rows = enriched.map(
  (z) =>
    `| [${z.identifier}](${z.url}) | ${z.title.slice(0, 60)}${z.title.length > 60 ? '…' : ''} | ${z.assignee} | ${z.hours}h | ${z.startedAt || 'unknown'} |`,
);

const sections = [
  `**Zombie count:** ${enriched.length}`,
  `**Threshold:** >${MAX_AGE_HOURS}h since startedAt with zero PR attachment.`,
  '',
  '| Issue | Title | Assignee | Hours Stalled | Started At |',
  '|---|---|---|---|---|',
  ...rows,
  '',
  '### Remediation',
  "1. Check for a stray branch that never got pushed: `git ls-remote origin | grep '<branch-name>'` (branch usually matches the issue's `gitBranchName`). Local-only work means the agent died mid-commit.",
  '2. If the work is abandoned: move the issue back to **Todo** to unclaim it, clear the assignee, and drop the `claude-task` label (or let another agent re-claim).',
  '3. If the work is still needed: spawn a fresh agent via `/start-task <IDENTIFIER>` so it re-enters the normal workflow.',
  '4. If the issue is bogus (agent hallucinated the task): close it as **canceled** with a one-line reason.',
  '',
  '---',
  `_Auto-generated by routines-hub W21 (agent-zombie). Daily scan at 20:45 UTC. Threshold: >${MAX_AGE_HOURS}h stalled with no PR link. Rolling singleton issue — heartbeats on match._`,
];

const longest = enriched[0];

const result = await ensureIssue({
  signature,
  onMatch: async (existing) => {
    await commentOnIssue(
      existing.id,
      `Zombie count: ${enriched.length}. Longest stall: ${longest.identifier} (${longest.hours}h).`,
    );
  },
  onNew: () => ({
    title,
    description: sections.join('\n'),
    projectKey: 'prod-health',
    labelNames: ['routine'],
    priority: 3,
  }),
});

console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
process.exit(0);
