// W23: Cognitive & Cyclomatic Complexity detector (weekly).
// SonarQube-parity scan for the "Intentional / Adaptable" Clean Code attributes.
// Per-function metrics across every TS/JS file in the target repo:
//   - Cognitive complexity (SonarQube algorithm via eslint-plugin-sonarjs)
//   - Cyclomatic complexity (typhonjs-escomplex)
//   - Function body LOC (typhonjs-escomplex sloc.logical)
//   - Parameter count (typhonjs-escomplex paramCount)
//
// Posts ONE rolling Linear issue per repo. Signature: [complexity:<repo>].
// Heartbeat on match (delta vs. prior scan); G1 CHECK 4 auto-closes when clear.
//
// Tooling notes:
//   typhonjs-escomplex + eslint-plugin-sonarjs are added as devDependencies of
//   routines-hub. The CI workflow runs `npm ci` (or `npm install`) inside the
//   routines-hub checkout before invoking this detector, so both libraries are
//   resolvable at runtime. If either import fails the detector posts a
//   "tooling unavailable in CI" skeleton issue and exits 0 — never silently
//   skips, because a missing analyzer is itself a complexity-tracking failure.

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, extname, relative } from 'node:path';
import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, TARGET_DIR } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!TARGET_DIR || !existsSync(TARGET_DIR)) {
  console.log(`No TARGET_DIR at ${TARGET_DIR} — skipping.`);
  process.exit(0);
}

// ----------------------------- Constants -----------------------------------

const CODE_EXTS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs']);
const SKIP_DIRS = new Set([
  'node_modules', 'dist', 'build', '.next', '.nuxt', '.cache',
  '.git', 'coverage', '__pycache__', '.venv', 'venv',
  'graphify-out', '.claude-flow', 'out', '.turbo', '.svelte-kit',
]);
const TEST_PATTERN = /\.(test|spec)\.[mc]?[tj]sx?$/;

// SonarQube default thresholds. See:
//   https://www.sonarsource.com/resources/cognitive-complexity/
//   https://docs.sonarsource.com/sonarqube-server/latest/user-guide/clean-code/
const T = {
  cogBlocker: 30,
  cogHigh: 15,
  cycHigh: 20,
  cycMedium: 10,
  bodyHigh: 100,
  bodyMedium: 50,
  paramHigh: 10,
  paramMedium: 7,
};

// SQALE-style remediation effort (minutes) per finding kind. Matches the
// per-finding minutes called out in the issue Remediation Playbook.
const EFFORT_MIN = {
  blocker: 45, // extract + refactor + tests
  high: 30,
  medium: 15,
  low: 5,
};

// ----------------------------- File walk -----------------------------------

function walkCodeFiles(dir, out = []) {
  let entries;
  try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const ent of entries) {
    if (ent.name.startsWith('.') && ent.name !== '.github') continue;
    const full = join(dir, ent.name);
    if (ent.isDirectory()) {
      if (SKIP_DIRS.has(ent.name)) continue;
      walkCodeFiles(full, out);
    } else if (ent.isFile() && CODE_EXTS.has(extname(ent.name)) && !TEST_PATTERN.test(ent.name)) {
      out.push(full);
    }
  }
  return out;
}

function countLines(path) {
  try { return readFileSync(path, 'utf8').split('\n').length; } catch { return 0; }
}

// --------------------------- Tool resolution -------------------------------

let escomplex = null;
let ESLint = null;
let sonarjs = null;
let tsparser = null;
let toolingError = null;

try {
  escomplex = (await import('typhonjs-escomplex')).default;
  ({ ESLint } = await import('eslint'));
  sonarjs = (await import('eslint-plugin-sonarjs')).default;
  tsparser = (await import('@typescript-eslint/parser')).default;
} catch (e) {
  toolingError = e;
}

// ------------------------ Skeleton issue path ------------------------------

async function postSkeletonAndExit(reason) {
  const signature = `[complexity:${TARGET_REPO}]`;
  const title = `${signature} tooling unavailable in CI`;
  const body = [
    `**Repo:** ${TARGET_REPO}`,
    `**Scan date:** ${new Date().toISOString()}`,
    '',
    '## Tooling unavailable',
    '',
    'Complexity analyzer failed to load in CI:',
    '',
    '```',
    reason,
    '```',
    '',
    'Required devDependencies in routines-hub:',
    '- `typhonjs-escomplex` (cyclomatic, LOC, params)',
    '- `eslint`, `eslint-plugin-sonarjs`, `@typescript-eslint/parser` (cognitive complexity)',
    '',
    '_Auto-generated by routines-hub W23 (complexity)._',
  ].join('\n');
  try {
    const result = await ensureIssue({
      signature,
      onMatch: async (existing) => {
        await commentOnIssue(
          existing.id,
          `Tooling still unavailable in ${TARGET_REPO} as of ${new Date().toISOString()}.\n\n\`${reason}\``,
        );
      },
      onNew: () => ({
        title,
        description: body,
        projectKey: 'code-health',
        labelNames: ['routine'],
        priority: 4,
      }),
    });
    console.log(`  ${result.action}: ${result.issue.identifier} — skeleton (${reason})`);
  } catch (e) {
    console.error(`  ERROR posting skeleton: ${e.message}`);
    process.exit(1);
  }
  process.exit(0);
}

if (toolingError) {
  await postSkeletonAndExit(`import failure: ${toolingError.message}`);
}

// --------------------------- Scanning --------------------------------------

console.log(`Scanning ${TARGET_REPO} for complexity…`);
const files = walkCodeFiles(TARGET_DIR);
console.log(`  Files in scope: ${files.length}`);

if (files.length === 0) {
  console.log(`${TARGET_REPO}: 0 source files in scope — no issue.`);
  process.exit(0);
}

// 1) Per-function cyclomatic / LOC / params via typhonjs-escomplex.
//    Yields: [{ file, name, line, cyclomatic, sloc, params }].
const escomplexFns = [];
let totalLOC = 0;
let analyzeErrors = 0;
for (const f of files) {
  let code;
  try { code = readFileSync(f, 'utf8'); } catch { continue; }
  totalLOC += code.split('\n').length;
  try {
    const report = escomplex.analyzeModule(code);
    for (const m of report.methods || []) {
      escomplexFns.push({
        file: relative(TARGET_DIR, f),
        name: m.name || '<anonymous>',
        line: m.lineStart || 0,
        cyclomatic: m.cyclomatic || 0,
        sloc: (m.sloc && m.sloc.logical) || 0,
        params: m.paramCount || 0,
      });
    }
  } catch {
    analyzeErrors++;
  }
}
console.log(`  escomplex: ${escomplexFns.length} functions across ${files.length - analyzeErrors} files (${analyzeErrors} parse errors)`);

// 2) Per-function cognitive complexity via eslint-plugin-sonarjs.
//    Threshold 0 surfaces every function with cognitive > 0.
//    Match key: `${relativePath}:${line}` — escomplex and ESLint agree on the
//    function's start line for top-level declarations. Function expressions /
//    arrows nested inside other functions sometimes diverge by 1; we tolerate
//    a ±1 line slop in the merge step below.
const eslint = new ESLint({
  cwd: TARGET_DIR,
  overrideConfigFile: true,
  overrideConfig: [{
    languageOptions: { parser: tsparser, ecmaVersion: 'latest', sourceType: 'module' },
    plugins: { sonarjs },
    rules: { 'sonarjs/cognitive-complexity': ['error', 0] },
  }],
});

// ESLint can lint many files at once — pass relative paths under cwd.
const relFiles = files.map((f) => relative(TARGET_DIR, f));
let eslintResults = [];
try {
  eslintResults = await eslint.lintFiles(relFiles);
} catch (e) {
  console.error(`  ESLint scan failed: ${e.message}`);
  // Fall through — we still have escomplex data, just no cognitive scores.
}

// Build cognitive map: file -> [{ line, cognitive }]
const cogMap = new Map();
for (const r of eslintResults) {
  const rel = relative(TARGET_DIR, r.filePath);
  const arr = [];
  for (const m of r.messages || []) {
    if (m.ruleId !== 'sonarjs/cognitive-complexity') continue;
    const match = m.message && m.message.match(/from (\d+) to/);
    if (!match) continue;
    arr.push({ line: m.line || 0, cognitive: Number(match[1]) });
  }
  if (arr.length) cogMap.set(rel, arr);
}
console.log(`  eslint sonarjs: cognitive scores for ${cogMap.size} files`);

// Merge cognitive into escomplex function records.
function pickCognitive(file, line) {
  const arr = cogMap.get(file);
  if (!arr) return 0;
  // Exact match first, then ±1.
  for (const e of arr) if (e.line === line) return e.cognitive;
  for (const e of arr) if (Math.abs(e.line - line) <= 1) return e.cognitive;
  return 0;
}
const fns = escomplexFns.map((fn) => ({ ...fn, cognitive: pickCognitive(fn.file, fn.line) }));

// ----------------------- Severity classification ---------------------------

function severityFor(fn) {
  // Highest of all violated thresholds wins.
  let s = null;
  if (fn.cognitive >= T.cogBlocker) s = 'Blocker';
  else if (fn.cognitive >= T.cogHigh || fn.cyclomatic >= T.cycHigh || fn.sloc >= T.bodyHigh || fn.params >= T.paramHigh) s = 'High';
  else if (fn.cyclomatic >= T.cycMedium || fn.sloc >= T.bodyMedium || fn.params >= T.paramMedium) s = 'Medium';
  return s;
}

function attributeFor(fn) {
  // SonarQube Clean Code mapping — Intentional vs Adaptable sub-attributes.
  if (fn.cognitive >= T.cogHigh) return 'Intentional → Clear';
  if (fn.cyclomatic >= T.cycMedium) return 'Intentional → Logical';
  if (fn.sloc >= T.bodyMedium) return 'Adaptable → Focused';
  if (fn.params >= T.paramMedium) return 'Adaptable → Modular';
  return 'Intentional → Clear';
}

const findings = [];
for (const fn of fns) {
  const sev = severityFor(fn);
  if (!sev) continue;
  findings.push({ ...fn, severity: sev, attribute: attributeFor(fn) });
}

// Tally by severity.
const counts = { Blocker: 0, High: 0, Medium: 0, Low: 0 };
for (const f of findings) counts[f.severity]++;

// --------------------------- Quality rating --------------------------------

const kLOC = Math.max(totalLOC / 1000, 0.001);
const violationsPerKLOC = findings.length / kLOC;
function rateMaintainability(perKLOC) {
  if (findings.length === 0) return 'A';
  if (perKLOC <= 5) return 'B';
  if (perKLOC <= 15) return 'C';
  if (perKLOC <= 30) return 'D';
  return 'E';
}
const ratings = { maintainability: rateMaintainability(violationsPerKLOC) };

console.log(`  Findings: blocker=${counts.Blocker} high=${counts.High} medium=${counts.Medium} total=${findings.length}`);
console.log(`  Rating: ${ratings.maintainability} (${violationsPerKLOC.toFixed(2)} per kLOC across ${totalLOC} LOC)`);

// Healthy → no issue.
if (findings.length === 0) {
  console.log(`${TARGET_REPO}: clean complexity (rating ${ratings.maintainability}) — no issue.`);
  process.exit(0);
}

// ------------------------------ Sorting ------------------------------------

// Worst offenders sorted by severity rank then cognitive desc.
const sevRank = { Blocker: 4, High: 3, Medium: 2, Low: 1 };
findings.sort((a, b) => {
  const r = sevRank[b.severity] - sevRank[a.severity];
  if (r !== 0) return r;
  return (b.cognitive || 0) - (a.cognitive || 0);
});
const top = findings.slice(0, 20);

// --------------------------- Effort estimate -------------------------------

const totalMinutes =
  counts.Blocker * EFFORT_MIN.blocker +
  counts.High * EFFORT_MIN.high +
  counts.Medium * EFFORT_MIN.medium +
  counts.Low * EFFORT_MIN.low;
const totalHours = (totalMinutes / 60).toFixed(1);

// --------------------------- Priority --------------------------------------

function computePriority(r) {
  if (r.maintainability === 'E') return 2; // High
  if (r.maintainability === 'D') return 2; // High
  if (r.maintainability === 'C') return 3; // Medium
  return 4;                                 // Low
}
const priority = computePriority(ratings);

// --------------------------- Issue body ------------------------------------

const signature = `[complexity:${TARGET_REPO}]`;
const title = `${signature} rating ${ratings.maintainability} — ${findings.length} complexity violation${findings.length === 1 ? '' : 's'} (B:${counts.Blocker} H:${counts.High} M:${counts.Medium})`;

// SAMPLE_OFFENDER is used in the Remediation Playbook to show a concrete
// example. We pick the highest-cognitive top function for relatability. If
// no offender body can be read, we fall back to a generic shape.
const sampleOffender = top[0] || null;
let sampleBefore = '// (no sample available)';
let sampleAfter = '// (no sample available)';
if (sampleOffender) {
  try {
    const abs = join(TARGET_DIR, sampleOffender.file);
    const lines = readFileSync(abs, 'utf8').split('\n');
    const start = Math.max(sampleOffender.line - 1, 0);
    // Show up to 12 lines from the function's start.
    const slice = lines.slice(start, start + 12).join('\n');
    sampleBefore =
      slice.length > 600
        ? slice.slice(0, 600) + '\n// … truncated …'
        : slice;
  } catch {
    // sampleBefore stays as the placeholder
  }
  sampleAfter = [
    `// Extract guard clauses + helpers:`,
    `function ${sampleOffender.name}(args) {`,
    `  if (!preconditionsMet(args)) return earlyResult;`,
    `  const intermediate = computeStep(args);`,
    `  return finalize(intermediate);`,
    `}`,
    `function preconditionsMet(args) { /* … */ }`,
    `function computeStep(args)      { /* … */ }`,
    `function finalize(x)            { /* … */ }`,
  ].join('\n');
}

// Top-20 table rows.
const topRows = top.map((f) =>
  `| \`${f.file}:${f.line}\` | \`${f.name.slice(0, 40)}\` | ${f.cognitive} | ${f.cyclomatic} | ${f.sloc} | ${f.params} | ${f.severity} | ${f.attribute} |`,
);

const body = [
  `**Repo:** ${TARGET_REPO}`,
  `**Scan date:** ${new Date().toISOString()}`,
  `**Files scanned:** ${files.length}`,
  `**Functions analyzed:** ${fns.length}`,
  `**Lines of code:** ${totalLOC}`,
  '',
  '## Quality Rating',
  '',
  '| Dimension | Rating | Violations | Trend |',
  '|---|---|---|---|',
  `| Maintainability | **${ratings.maintainability}** | ${findings.length} (${violationsPerKLOC.toFixed(2)} / kLOC) | first scan |`,
  '',
  'Applies to SonarQube Clean Code attributes: **Intentional** (Clear, Logical, Complete, Efficient) and **Adaptable** (Focused, Distinct, Modular).',
  '',
  '## Findings by Severity',
  '',
  '| Severity | Count | Rule |',
  '|---|---|---|',
  `| Blocker | ${counts.Blocker} | Cognitive complexity ≥ ${T.cogBlocker} |`,
  `| High    | ${counts.High}    | Cognitive complexity ≥ ${T.cogHigh} / Cyclomatic ≥ ${T.cycHigh} / Body ≥ ${T.bodyHigh} LOC / Params ≥ ${T.paramHigh} |`,
  `| Medium  | ${counts.Medium}  | Cyclomatic ≥ ${T.cycMedium} / Body ≥ ${T.bodyMedium} LOC / Params ≥ ${T.paramMedium} |`,
  `| Low     | ${counts.Low}     | (reserved — Params ≥ 5 in hot-path files) |`,
  '',
  `## Top ${Math.min(20, findings.length)} Offenders`,
  '',
  '| File:Line | Function | Cognitive | Cyclomatic | LOC | Params | Severity | Clean Code Attribute |',
  '|---|---|---|---|---|---|---|---|',
  ...topRows,
  '',
  '## Findings by Software Quality',
  '',
  `**Maintainability** (primary) — ${findings.length} findings. These functions are hard to understand, test, and modify. Each additional unit of complexity compounds the risk of introducing bugs during future changes.`,
  '',
  '**Reliability** (secondary) — high-complexity functions have statistically higher defect rates (SonarQube research: functions with cognitive complexity > 15 are roughly 3x more likely to contain bugs than simpler ones).',
  '',
  '## Remediation Playbook',
  '',
  `### Extract function (cognitive complexity ≥ ${T.cogHigh})`,
  '',
  `Worst offender today: \`${sampleOffender ? sampleOffender.file + ':' + sampleOffender.line : 'n/a'}\` — \`${sampleOffender ? sampleOffender.name : 'n/a'}\` (cognitive=${sampleOffender ? sampleOffender.cognitive : 0}).`,
  '',
  'Before:',
  '```ts',
  sampleBefore,
  '```',
  '',
  'After:',
  '```ts',
  sampleAfter,
  '```',
  '',
  `**Effort:** ~${EFFORT_MIN.high} minutes per function. Goal: each helper <15 cognitive complexity.`,
  '',
  '### Guard-clause early returns (deep nesting)',
  '',
  'Replace deep `if (a) { if (b) { if (c) { … } } }` chains with early returns. Each early return removes a level of nesting weight from the cognitive score.',
  '',
  `**Effort:** ~${EFFORT_MIN.medium} minutes per function.`,
  '',
  '### Parameter object (long parameter list)',
  '',
  `Functions with ≥ ${T.paramMedium} parameters are hard to call correctly and hide coupling. Replace with a single options object: \`function f(opts: { a, b, c, … })\`.`,
  '',
  `**Effort:** ~${EFFORT_MIN.high} minutes per function plus call-site updates.`,
  '',
  '## Historical Trend',
  '',
  'First scan. Subsequent heartbeats will show delta from prior scan.',
  '',
  '## Effort Estimate',
  '',
  `**Total:** ~${totalHours} hours to bring Maintainability rating to A (estimated from per-finding effort × count, using SonarQube's SQALE model where available).`,
  '',
  '## References',
  '',
  '- [SonarQube cognitive complexity](https://www.sonarsource.com/resources/cognitive-complexity/) — threshold 15 is the SonarQube default.',
  '- [Clean Code: Adaptable](https://docs.sonarsource.com/sonarqube-server/latest/user-guide/clean-code/) — Focused, Distinct, Modular sub-attributes.',
  '- [SQALE method](https://en.wikipedia.org/wiki/SQALE) — technical debt estimation basis.',
  '',
  '<!-- routines-hub:complexity:metrics',
  JSON.stringify({
    findings: findings.length,
    counts,
    rating: ratings.maintainability,
    perKLOC: Number(violationsPerKLOC.toFixed(3)),
    LOC: totalLOC,
    files: files.length,
    functions: fns.length,
    worst: sampleOffender ? { file: sampleOffender.file, line: sampleOffender.line, name: sampleOffender.name, cognitive: sampleOffender.cognitive } : null,
  }),
  '-->',
  '',
  '---',
  '',
  `*Auto-generated by routines-hub W23 (complexity). Weekly scan. Signature: \`${signature}\`. Auto-closes via G1 when clear for 3d.*`,
].join('\n');

// --------------------- Heartbeat (delta vs. prior) -------------------------

// Previous scan metrics live inside an HTML comment on the issue body. The
// heartbeat parses them out, computes delta, and posts a comment. If parsing
// fails we just report current numbers — never hard-fail.
function parsePriorMetrics(description) {
  if (!description || typeof description !== 'string') return null;
  const m = description.match(/<!--\s*routines-hub:complexity:metrics\s*([\s\S]*?)\s*-->/);
  if (!m) return null;
  try { return JSON.parse(m[1]); } catch { return null; }
}

async function heartbeat(existing) {
  const prior = parsePriorMetrics(existing.description);
  const worst = sampleOffender;
  const worstLine = worst
    ? `Worst offender: \`${worst.file}:${worst.line}\` \`${worst.name}\` cognitive=${worst.cognitive}.`
    : 'No top offender available.';
  let line2;
  if (prior && typeof prior.findings === 'number') {
    const delta = findings.length - prior.findings;
    const sign = delta > 0 ? `+${delta}` : `${delta}`;
    const ratingNote = prior.rating === ratings.maintainability ? `Rating ${ratings.maintainability}` : `Rating ${ratings.maintainability} (was ${prior.rating})`;
    line2 = `Current: **${findings.length} violations** (was ${prior.findings} — Δ${sign}). ${ratingNote}.`;
  } else {
    line2 = `Current: **${findings.length} violations**. Rating ${ratings.maintainability}. (Prior metrics unavailable for delta.)`;
  }
  await commentOnIssue(
    existing.id,
    `Still tracking complexity in ${TARGET_REPO} as of ${new Date().toISOString()}.\n${line2}\n${worstLine}`,
  );
}

try {
  const result = await ensureIssue({
    signature,
    onMatch: heartbeat,
    onNew: () => ({
      title,
      description: body,
      projectKey: 'code-health',
      labelNames: ['routine'],
      priority,
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
