// W7: Dead Code detector (daily) using knip.
// Parses knip --reporter json and posts a rolling digest of unused files,
// exports, types, dependencies, and devDependencies.
//
// Signature: [dead-code:<repo>]  — one rolling issue per repo.
// Heartbeat on match; G1 CHECK 4 auto-closes when all signals clear for 3d.

import { readFileSync, existsSync } from 'node:fs';
import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, KNIP_JSON } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!KNIP_JSON || !existsSync(KNIP_JSON)) {
  console.log(`No knip.json at ${KNIP_JSON} — skipping.`);
  process.exit(0);
}

let report;
try {
  report = JSON.parse(readFileSync(KNIP_JSON, 'utf8'));
} catch (e) {
  console.log(`Failed to parse knip.json: ${e.message}`);
  process.exit(0);
}

// knip JSON shapes vary by version. Normalize defensively.
const files = Array.isArray(report.files) ? report.files : [];
const issues = Array.isArray(report.issues) ? report.issues : [];

const counts = {
  files: files.length,
  exports: 0,
  types: 0,
  dependencies: 0,
  devDependencies: 0,
  unlisted: 0,
  duplicates: 0,
};
const examples = {
  files: files.slice(0, 10),
  exports: [],
  dependencies: [],
};

for (const i of issues) {
  const bucketize = (key, countOnly = false) => {
    const val = i[key];
    if (!val) return;
    if (Array.isArray(val)) {
      counts[key] = (counts[key] || 0) + val.length;
      if (!countOnly && examples[key] && examples[key].length < 10) {
        for (const v of val) {
          if (examples[key].length >= 10) break;
          const name = typeof v === 'string' ? v : v.name || v.symbol || JSON.stringify(v);
          examples[key].push(`${i.file || ''}: ${name}`);
        }
      }
    } else if (typeof val === 'object') {
      counts[key] = (counts[key] || 0) + Object.keys(val).length;
    }
  };
  bucketize('exports');
  bucketize('types', true);
  bucketize('dependencies');
  bucketize('devDependencies', true);
  bucketize('unlisted', true);
  bucketize('duplicates', true);
}

const total =
  counts.files +
  counts.exports +
  counts.types +
  counts.dependencies +
  counts.devDependencies +
  counts.unlisted +
  counts.duplicates;

const THRESHOLD = 10;
if (total < THRESHOLD) {
  console.log(`${TARGET_REPO}: ${total} dead-code items — below threshold ${THRESHOLD}, no issue.`);
  process.exit(0);
}

const signature = `[dead-code:${TARGET_REPO}]`;
const title = `${signature} ${total} dead-code items — ${counts.files}f / ${counts.exports}ex / ${counts.dependencies}deps`;

const sections = [
  `**Repo:** ${TARGET_REPO}`,
  `**Total dead-code items:** ${total}`,
  '',
  '| Kind | Count |',
  '|---|---|',
  `| Unused files | ${counts.files} |`,
  `| Unused exports | ${counts.exports} |`,
  `| Unused types | ${counts.types} |`,
  `| Unused dependencies | ${counts.dependencies} |`,
  `| Unused devDependencies | ${counts.devDependencies} |`,
  `| Unlisted (used but not declared) | ${counts.unlisted} |`,
  `| Duplicate exports | ${counts.duplicates} |`,
  '',
];

if (examples.files.length) {
  sections.push('### Unused files (top 10)');
  for (const f of examples.files) sections.push(`- \`${f}\``);
  sections.push('');
}
if (examples.exports.length) {
  sections.push('### Unused exports (top 10)');
  for (const e of examples.exports) sections.push(`- \`${e}\``);
  sections.push('');
}
if (examples.dependencies.length) {
  sections.push('### Unused dependencies (top 10)');
  for (const d of examples.dependencies) sections.push(`- \`${d}\``);
  sections.push('');
}

sections.push('---');
sections.push(
  '_Auto-generated by routines-hub W7 (dead-code via knip). Daily scan; one rolling issue per repo. Auto-closes via G1 when cleared._',
);
sections.push('');
sections.push('Fix: `npx knip` locally; `npm uninstall` unused deps; delete unused files/exports; ship in one PR.');

try {
  const result = await ensureIssue({
    signature,
    onMatch: async (existing) => {
      await commentOnIssue(
        existing.id,
        `Still present in ${TARGET_REPO} as of ${new Date().toISOString()}.\n` +
          `Current: **${total} items** (${counts.files} files, ${counts.exports} exports, ${counts.dependencies} deps, ${counts.devDependencies} devDeps).`,
      );
    },
    onNew: () => ({
      title,
      description: sections.join('\n'),
      projectKey: 'code-health',
      labelNames: ['routine'],
      priority: 4, // Low — slow-burn tech debt
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
