// W9: Code Duplication detector (daily) using jscpd.
// Parses jscpd --reporters json output and posts a rolling digest of
// duplication percentage and top clones.
//
// Signature: [dupes:<repo>]  — one rolling issue per repo.
// Heartbeat on match; G1 CHECK 4 auto-closes when duplication drops below
// threshold for 3d.

import { readFileSync, existsSync } from 'node:fs';
import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, JSCPD_JSON } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!JSCPD_JSON || !existsSync(JSCPD_JSON)) {
  console.log(`No jscpd report at ${JSCPD_JSON} — skipping.`);
  process.exit(0);
}

let report;
try {
  report = JSON.parse(readFileSync(JSCPD_JSON, 'utf8'));
} catch (e) {
  console.log(`Failed to parse jscpd.json: ${e.message}`);
  process.exit(0);
}

const stats = report.statistics?.total || {};
const percentage = Number(stats.percentage ?? 0);
const duplicatedLines = Number(stats.duplicatedLines ?? 0);
const totalLines = Number(stats.lines ?? 0);
const totalFiles = Number(stats.files ?? 0);
const duplicates = Array.isArray(report.duplicates) ? report.duplicates : [];
const clonedFiles = Number(stats.clones ?? duplicates.length);

const PERCENTAGE_THRESHOLD = 3.0; // >3% duplication is noteworthy
const COUNT_THRESHOLD = 20; // or 20+ clones

if (percentage < PERCENTAGE_THRESHOLD && clonedFiles < COUNT_THRESHOLD) {
  console.log(
    `${TARGET_REPO}: ${percentage.toFixed(2)}% / ${clonedFiles} clones — below threshold.`,
  );
  process.exit(0);
}

const signature = `[dupes:${TARGET_REPO}]`;
const title = `${signature} ${percentage.toFixed(1)}% duplication — ${clonedFiles} clone${clonedFiles === 1 ? '' : 's'}`;

const topClones = duplicates
  .slice()
  .sort((a, b) => (b.lines || 0) - (a.lines || 0))
  .slice(0, 10)
  .map((d) => {
    const a = d.firstFile || d.file || {};
    const b = d.secondFile || d.other || {};
    const aStr = `${a.name || a.path || '?'}:${a.start || a.startLoc?.line || ''}`;
    const bStr = `${b.name || b.path || '?'}:${b.start || b.startLoc?.line || ''}`;
    const loc = d.lines || d.tokens || d.duplicatedLines || '?';
    return `- \`${aStr}\` ↔ \`${bStr}\` (${loc} lines)`;
  });

const sections = [
  `**Repo:** ${TARGET_REPO}`,
  `**Duplication:** ${percentage.toFixed(2)}%`,
  `**Clones detected:** ${clonedFiles}`,
  `**Duplicated lines:** ${duplicatedLines.toLocaleString()} / ${totalLines.toLocaleString()}`,
  `**Files scanned:** ${totalFiles}`,
  '',
];

if (topClones.length) {
  sections.push('### Top 10 clones (by LOC)');
  sections.push('');
  sections.push(...topClones);
  sections.push('');
}

sections.push('---');
sections.push(
  '_Auto-generated by routines-hub W9 (duplication via jscpd, min 10 lines). Daily scan; one rolling issue per repo. Auto-closes via G1 when duplication drops below threshold._',
);

try {
  const result = await ensureIssue({
    signature,
    onMatch: async (existing) => {
      await commentOnIssue(
        existing.id,
        `Still present in ${TARGET_REPO} as of ${new Date().toISOString()}.\n` +
          `Current: **${percentage.toFixed(2)}% duplication** across **${clonedFiles} clone${clonedFiles === 1 ? '' : 's'}**.`,
      );
    },
    onNew: () => ({
      title,
      description: sections.join('\n'),
      projectKey: 'code-health',
      labelNames: ['routine'],
      priority: 4, // Low — slow-burn tech debt
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
