// W22: iCloud-dupes detector (daily).
// iCloud Drive's sync sometimes clones existing files with a " N" suffix
// (e.g. `routes.ts` → `routes 2.ts`, or dir `.claude/` → `.claude 2/`).
// When those get `git add .`-ed they pollute the repo and can even corrupt
// `.git` refs (observed 2026-04-18: 5dsmiles-dashboard needed a fresh clone;
// 2026-04-19: sleep_test_scheduler had `refs/remotes 2/origin/...` badRefName).
//
// This detector runs `git ls-files` inside the target checkout, filters for
// the " N." filename suffix (before extension) OR a " N/" path-segment
// suffix (directory dupes), and posts a rolling Linear issue per repo.
//
// Signature: [icloud-dupes:<repo>]  — one rolling issue per repo.
// Heartbeat on match; G1 CHECK 4 auto-closes after 3d of silence.

import { existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, TARGET_DIR } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!TARGET_DIR || !existsSync(TARGET_DIR)) {
  console.log(`No TARGET_DIR at ${TARGET_DIR} — skipping.`);
  process.exit(0);
}

// File-level dupes: ` 2.ts`, ` 3.tsx`, etc. before the extension.
const FILENAME_DUPE_RE =
  / \d+\.(ts|tsx|js|jsx|mjs|cjs|json|py|md|yml|yaml|css|html|sql|sh|toml)$/;
// Directory-level dupes: any path segment ending in ` 2`, ` 3`, etc. (e.g.
// `refs/remotes 2/origin/head` or `.claude 2/config.json`). Matches when a
// " N/" appears anywhere in the path.
const DIR_DUPE_RE = / \d+\//;

function classify(path) {
  if (DIR_DUPE_RE.test(path)) return 'directory';
  if (FILENAME_DUPE_RE.test(path)) return 'filename';
  return null;
}

let trackedFiles;
try {
  const out = execSync(
    `git -C ${JSON.stringify(TARGET_DIR)} ls-files`,
    { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], maxBuffer: 16 * 1024 * 1024 },
  );
  trackedFiles = out.split('\n').filter(Boolean);
} catch (e) {
  console.error(`  ERROR: git ls-files failed in ${TARGET_DIR} — ${e.message}`);
  process.exit(1);
}

const matches = [];
for (const path of trackedFiles) {
  const category = classify(path);
  if (category) matches.push({ path, category });
}

if (matches.length === 0) {
  console.log(`${TARGET_REPO}: no iCloud dupes — no issue.`);
  process.exit(0);
}

matches.sort((a, b) => a.path.localeCompare(b.path));

const signature = `[icloud-dupes:${TARGET_REPO}]`;
const title = `${signature} ${matches.length} file${matches.length === 1 ? '' : 's'} with " N." iCloud-sync suffix committed to git`;

const shown = matches.slice(0, 25);
const rows = shown.map((m) => `| \`${m.path}\` | ${m.category} |`);

const sections = [
  `**Repo:** ${TARGET_REPO}`,
  `**iCloud-dupe paths tracked in git:** ${matches.length}${matches.length > 25 ? ` (showing first 25)` : ''}`,
  '',
  '| File | Category |',
  '|---|---|',
  ...rows,
  '',
  '### Remediation',
  '1. Remove each path from the index (keeps nothing on disk — these are iCloud-created duplicates):',
  '',
  '```sh',
  ...shown.map((m) => `git rm --cached ${JSON.stringify(m.path)}`),
  '```',
  '',
  '2. Add the iCloud-dupe pattern to `.gitignore` so future dupes never get staged:',
  '',
  '```gitignore',
  '* [0-9].*',
  '```',
  '',
  '3. Investigate iCloud Drive sync on the `~/Documents/' + TARGET_REPO + '/` directory on the machine that produced the commit. Consider moving the repo **outside** iCloud-synced Documents (e.g. `~/Code/`) — iCloud sync on a working git repo is the root cause (see 2026-04-18 5dsmiles-dashboard incident, 2026-04-19 sleep_test_scheduler `refs/remotes 2/` badRefName).',
  '',
  '---',
  '_Auto-generated by routines-hub W22 (icloud-dupes). Daily scan. Auto-closes via G1 when clear for 3d._',
];

const sampleForComment = matches[0];

try {
  const result = await ensureIssue({
    signature,
    onMatch: async (existing) => {
      await commentOnIssue(
        existing.id,
        `Still present in ${TARGET_REPO} as of ${new Date().toISOString()}.\n` +
          `Current: **${matches.length} iCloud-dupe path${matches.length === 1 ? '' : 's'}** (sample: \`${sampleForComment.path}\` — ${sampleForComment.category}).`,
      );
    },
    onNew: () => ({
      title,
      description: sections.join('\n'),
      projectKey: 'code-health',
      labelNames: ['routine'],
      priority: 3, // Medium — bloats repo, can corrupt .git refs
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
