// W10: Outdated Majors detector (daily).
// Parses `npm outdated --json --long` and posts ONE rolling Linear issue per
// repo listing every direct dependency that is at least one major behind.
// Signature: [deps:majors:<repo>]  — one rolling issue per repo.
//
// The daily run posts a "Still present" heartbeat when an existing issue is
// matched, so G1 CHECK 4 auto-closes once the repo catches up.

import { readFileSync, existsSync } from 'node:fs';
import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, OUTDATED_JSON } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!OUTDATED_JSON || !existsSync(OUTDATED_JSON)) {
  console.log(`No outdated.json at ${OUTDATED_JSON} — skipping.`);
  process.exit(0);
}

const raw = readFileSync(OUTDATED_JSON, 'utf8').trim();
if (!raw) {
  console.log(`${TARGET_REPO}: no outdated packages.`);
  process.exit(0);
}

let outdated;
try {
  outdated = JSON.parse(raw);
} catch (e) {
  console.log(`Failed to parse outdated.json: ${e.message}`);
  process.exit(0);
}

function majorOf(v) {
  if (!v) return null;
  // Accept 1.2.3, v1.2.3, 1.2.3-beta.0, etc.
  const m = /^v?(\d+)\./.exec(v);
  return m ? Number.parseInt(m[1], 10) : null;
}

// Build the list of direct deps at least 1 major behind `wanted`.
// `wanted` = highest version allowed by current semver range in package.json.
// `latest` = newest published version.
// We flag: (latest.major - current.major) >= 1.
const entries = [];
for (const [pkg, info] of Object.entries(outdated)) {
  if (info.type && info.type !== 'dependencies' && info.type !== 'devDependencies') continue;
  const currentMaj = majorOf(info.current);
  const latestMaj = majorOf(info.latest);
  if (currentMaj == null || latestMaj == null) continue;
  const behind = latestMaj - currentMaj;
  if (behind < 1) continue;
  entries.push({
    pkg,
    current: info.current,
    wanted: info.wanted,
    latest: info.latest,
    type: info.type || 'dependencies',
    behind,
    homepage: info.homepage,
  });
}

if (entries.length === 0) {
  console.log(`${TARGET_REPO}: no major updates available.`);
  process.exit(0);
}

// Sort: most-behind first, then alphabetical
entries.sort((a, b) => b.behind - a.behind || a.pkg.localeCompare(b.pkg));

console.log(`${TARGET_REPO}: ${entries.length} package(s) ≥1 major behind.`);

const signature = `[deps:majors:${TARGET_REPO}]`;

// Build markdown table
const header = [
  '| Package | Current | Latest | Majors behind | Kind |',
  '|---|---|---|---|---|',
];
const rows = entries.map((e) => {
  const linkOrPkg = e.homepage ? `[${e.pkg}](${e.homepage})` : e.pkg;
  return `| ${linkOrPkg} | ${e.current} | ${e.latest} | ${e.behind} | ${e.type} |`;
});

const title = `${signature} ${entries.length} major update${entries.length === 1 ? '' : 's'} available`;
const body = [
  `**Repo:** ${TARGET_REPO}`,
  `**Total packages ≥1 major behind:** ${entries.length}`,
  '',
  ...header,
  ...rows,
  '',
  '### Next actions',
  '1. Review each entry for breaking changes (check release notes)',
  '2. Batch compatible upgrades into one PR: `npm install pkg@latest`',
  '3. Run tests; ship; close this issue',
  '',
  '_Auto-generated by routines-hub W10 (outdated-majors). Daily scan; one rolling issue per repo. Auto-closes via G1 when caught up._',
].join('\n');

try {
  const result = await ensureIssue({
    signature,
    onMatch: async (existing) => {
      await commentOnIssue(
        existing.id,
        `Still present in ${TARGET_REPO} as of ${new Date().toISOString()}.\n` +
          `Current: **${entries.length} package${entries.length === 1 ? '' : 's'} ≥1 major behind**.`,
      );
    },
    onNew: () => ({
      title,
      description: body,
      projectKey: 'dependencies',
      labelNames: ['routine'],
      priority: 3, // Medium
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
