// W13: Secrets History detector (daily) using gitleaks.
// Complements W6 (Semgrep scans working tree only) by scanning the FULL git
// history for previously-committed secrets. Catches tokens/keys that were
// committed, then deleted but still live forever in git log.
//
// Signature: [secrets-history:<repo>]  — one rolling issue per repo.
// Dedup: ensureIssue → findOpenIssueBySignature → startsWith title match +
//        open-state filter. Heartbeat on match; G1 CHECK 4 auto-closes after
//        3d of silence.

import { readFileSync, existsSync } from 'node:fs';
import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, GITLEAKS_JSON } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!GITLEAKS_JSON || !existsSync(GITLEAKS_JSON)) {
  console.log(`No gitleaks report at ${GITLEAKS_JSON} — skipping.`);
  process.exit(0);
}

let findings;
try {
  const raw = readFileSync(GITLEAKS_JSON, 'utf8').trim();
  findings = raw ? JSON.parse(raw) : [];
} catch (e) {
  console.log(`Failed to parse gitleaks.json: ${e.message}`);
  process.exit(0);
}

if (!Array.isArray(findings) || findings.length === 0) {
  console.log(`${TARGET_REPO}: 0 gitleaks findings — no issue.`);
  process.exit(0);
}

// Group by rule and get unique file hits
const byRule = {};
const uniqueFiles = new Set();
for (const f of findings) {
  const rule = f.RuleID || f.Rule || 'unknown';
  byRule[rule] = (byRule[rule] || 0) + 1;
  if (f.File) uniqueFiles.add(f.File);
}

const total = findings.length;
const ruleCount = Object.keys(byRule).length;
const fileCount = uniqueFiles.size;

const signature = `[secrets-history:${TARGET_REPO}]`;
const title = `${signature} ${total} secret leak${total === 1 ? '' : 's'} in git history — ${ruleCount} rule${ruleCount === 1 ? '' : 's'}, ${fileCount} file${fileCount === 1 ? '' : 's'}`;

const ruleRows = Object.entries(byRule)
  .sort(([, a], [, b]) => b - a)
  .slice(0, 10)
  .map(([rule, n]) => `| \`${rule}\` | ${n} |`);

// Top 10 findings with redacted match
const topFindings = findings.slice(0, 10).map((f) => {
  const commit = (f.Commit || '').slice(0, 7);
  const file = f.File || '?';
  const line = f.StartLine || f.Line || '?';
  const rule = f.RuleID || f.Rule || '?';
  const date = (f.Date || '').slice(0, 10);
  return `- \`${file}:${line}\` — **${rule}** (commit ${commit}, ${date})`;
});

const sections = [
  `**Repo:** ${TARGET_REPO}`,
  `**Total findings in git history:** ${total}`,
  `**Unique rules tripped:** ${ruleCount}`,
  `**Unique files:** ${fileCount}`,
  '',
  '### Findings by rule',
  '',
  '| Rule | Count |',
  '|---|---|',
  ...ruleRows,
  '',
  '### Sample findings (first 10)',
  '',
  ...topFindings,
  '',
  '### Remediation',
  '',
  '1. **Rotate the leaked secrets immediately.** Even if the commit was deleted, the secret is in git history forever and must be assumed compromised.',
  '2. Review each finding — confirm it\'s a real secret vs false positive.',
  '3. For real leaks: rotate, then (optionally) rewrite history via `git filter-repo` or BFG. This is disruptive and coordinated with the team.',
  '4. Add the pattern to `.gitleaks.toml` allowlist if it\'s a test fixture / public sample (proven safe).',
  '',
  '---',
  '_Auto-generated by routines-hub W13 (secrets-history via gitleaks). Daily full-history scan. Auto-closes via G1 when cleared for 3d._',
];

try {
  const result = await ensureIssue({
    signature,
    onMatch: async (existing) => {
      await commentOnIssue(
        existing.id,
        `Still present in ${TARGET_REPO} as of ${new Date().toISOString()}.\n` +
          `Current: **${total} findings** across **${ruleCount} rule${ruleCount === 1 ? '' : 's'}** in **${fileCount} file${fileCount === 1 ? '' : 's'}**.`,
      );
    },
    onNew: () => ({
      title,
      description: sections.join('\n'),
      projectKey: 'security-hygiene',
      labelNames: ['routine', 'compliance'],
      priority: 1, // P1 — leaked secrets are urgent
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
