// W6: Semgrep detector (daily).
// Parses `semgrep --json` output for a repo and posts a rolling Linear issue
// digesting ERROR + WARNING findings. Signature is undated so the issue persists
// day-to-day; the daily run posts a "Still present" heartbeat so the groomer
// (G1 CHECK 4) can auto-close when findings go to zero.
//
// Signature: [semgrep:<repo>]  — one rolling issue per repo.
//
// Env:
//   LINEAR_API_KEY (required)
//   TARGET_REPO    (required)
//   SEMGREP_JSON   (required — path to semgrep --json output)

import { readFileSync, existsSync } from 'node:fs';
import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, SEMGREP_JSON } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!SEMGREP_JSON || !existsSync(SEMGREP_JSON)) {
  console.log(`No semgrep.json at ${SEMGREP_JSON} — skipping.`);
  process.exit(0);
}

let report;
try {
  report = JSON.parse(readFileSync(SEMGREP_JSON, 'utf8'));
} catch (e) {
  console.log(`Failed to parse semgrep.json: ${e.message}`);
  process.exit(0);
}

const results = Array.isArray(report.results) ? report.results : [];

// Filter to WARNING + ERROR severity. INFO is too noisy for a daily digest.
const bySeverity = { ERROR: [], WARNING: [] };
for (const r of results) {
  const sev = (r.extra?.severity || '').toUpperCase();
  if (sev === 'ERROR' || sev === 'WARNING') bySeverity[sev].push(r);
}

const total = bySeverity.ERROR.length + bySeverity.WARNING.length;
if (total === 0) {
  console.log(`${TARGET_REPO}: 0 semgrep findings (ERROR/WARNING) — no issue.`);
  process.exit(0);
}

// Group by rule
const byRule = new Map();
for (const r of [...bySeverity.ERROR, ...bySeverity.WARNING]) {
  const ruleId = r.check_id || 'unknown';
  if (!byRule.has(ruleId)) {
    byRule.set(ruleId, {
      sev: (r.extra?.severity || '').toUpperCase(),
      count: 0,
      examples: [],
    });
  }
  const group = byRule.get(ruleId);
  group.count++;
  if (group.examples.length < 3) {
    group.examples.push({
      path: r.path || '',
      line: r.start?.line || 0,
      message: (r.extra?.message || '').split('\n')[0].slice(0, 160),
    });
  }
}

const rulesSorted = [...byRule.entries()].sort(([, a], [, b]) => {
  if (a.sev !== b.sev) return a.sev === 'ERROR' ? -1 : 1;
  return b.count - a.count;
});

const signature = `[semgrep:${TARGET_REPO}]`;
const title = `${signature} ${bySeverity.ERROR.length} errors, ${bySeverity.WARNING.length} warnings — ${byRule.size} rule${byRule.size === 1 ? '' : 's'}`;

const sections = [
  `**Repo:** ${TARGET_REPO}`,
  `**Total findings:** ${total} (${bySeverity.ERROR.length} ERROR, ${bySeverity.WARNING.length} WARNING)`,
  `**Configs:** p/security-audit · p/secrets · p/owasp-top-ten`,
  '',
  '### Findings by rule (top 20)',
  '',
  '| Severity | Rule | Count | Example |',
  '|---|---|---|---|',
];
for (const [ruleId, group] of rulesSorted.slice(0, 20)) {
  const ex = group.examples[0];
  const exStr = ex ? `\`${ex.path}:${ex.line}\`` : '';
  sections.push(`| ${group.sev} | \`${ruleId}\` | ${group.count} | ${exStr} |`);
}
sections.push('');
sections.push('### Top 5 rules — full examples');
sections.push('');
for (const [ruleId, group] of rulesSorted.slice(0, 5)) {
  sections.push(`**\`${ruleId}\`** · ${group.sev} · ${group.count} finding${group.count === 1 ? '' : 's'}`);
  for (const ex of group.examples) {
    sections.push(`- \`${ex.path}:${ex.line}\` — ${ex.message}`);
  }
  sections.push('');
}
sections.push('---');
sections.push('_Auto-generated by routines-hub W6 (semgrep). Daily scan; one rolling issue per repo. Auto-closes via G1 when findings clear._');

const priority = bySeverity.ERROR.length > 0 ? 2 : 3; // High if any ERROR, Medium otherwise

try {
  const result = await ensureIssue({
    signature,
    onMatch: async (existing) => {
      await commentOnIssue(
        existing.id,
        `Still present in ${TARGET_REPO} as of ${new Date().toISOString()}.\n` +
          `Current counts: **${bySeverity.ERROR.length} ERROR, ${bySeverity.WARNING.length} WARNING** across **${byRule.size} rule${byRule.size === 1 ? '' : 's'}**.`,
      );
    },
    onNew: () => ({
      title,
      description: sections.join('\n'),
      projectKey: 'security-hygiene',
      labelNames: ['routine', 'compliance'],
      priority,
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
