// W15: Stale PRs detector (daily).
// Queries GitHub GraphQL for every open PR in a repo and flags ones untouched
// for >7 days (drafts included — they rot too). Posts a rolling Linear issue
// per repo listing the stale PRs and their authors.
//
// Signature: [stale-prs:<repo>]  — one rolling issue per repo.
// Dedup: ensureIssue → startsWith title match + open-state filter. Heartbeat
//        on match; G1 CHECK 4 auto-closes after 3d of silence.

import { ensureIssue, commentOnIssue } from '../lib/linear.mjs';

const { TARGET_REPO, GITHUB_TOKEN } = process.env;
if (!TARGET_REPO) throw new Error('TARGET_REPO required');
if (!GITHUB_TOKEN) throw new Error('GITHUB_TOKEN required (repo read scope)');

const OWNER = 'Wakewell-Sleep-Solutions';
const STALE_DAYS = 7;
const THRESHOLD_COUNT = 1; // any stale PR warrants a ping

async function gh(query, variables = {}) {
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query, variables }),
  });
  const json = await res.json();
  if (json.errors) throw new Error(`GitHub GraphQL error: ${JSON.stringify(json.errors)}`);
  return json.data;
}

const data = await gh(
  `query StalePRs($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
      pullRequests(states: OPEN, first: 50, orderBy: { field: UPDATED_AT, direction: ASC }) {
        nodes {
          number
          title
          url
          updatedAt
          createdAt
          isDraft
          author { login }
        }
      }
    }
  }`,
  { owner: OWNER, name: TARGET_REPO },
);

const repo = data.repository;
if (!repo) {
  console.log(`${TARGET_REPO}: repo not found via GraphQL — skipping.`);
  process.exit(0);
}

const now = Date.now();
const threshold = now - STALE_DAYS * 86400000;

const stalePrs = [];
for (const pr of repo.pullRequests.nodes) {
  const updated = new Date(pr.updatedAt).getTime();
  if (updated > threshold) continue;
  stalePrs.push({
    number: pr.number,
    title: pr.title,
    url: pr.url,
    author: pr.author?.login || 'unknown',
    updatedAt: pr.updatedAt,
    createdAt: pr.createdAt,
    days: Math.floor((now - updated) / 86400000),
    isDraft: pr.isDraft,
  });
}

stalePrs.sort((a, b) => b.days - a.days);

if (stalePrs.length < THRESHOLD_COUNT) {
  console.log(`${TARGET_REPO}: 0 stale PRs — no issue.`);
  process.exit(0);
}

const signature = `[stale-prs:${TARGET_REPO}]`;
const title = `${signature} ${stalePrs.length} PR${stalePrs.length === 1 ? '' : 's'} untouched ≥${STALE_DAYS}d`;

const rows = stalePrs.map(
  (p) =>
    `| [#${p.number}](${p.url}) | ${p.title.slice(0, 60)}${p.title.length > 60 ? '…' : ''} | ${p.author} | ${p.days}d | ${p.isDraft ? 'draft' : 'open'} |`,
);

const sections = [
  `**Repo:** ${TARGET_REPO}`,
  `**Stale PRs (>${STALE_DAYS}d no activity):** ${stalePrs.length}`,
  '',
  '| PR | Title | Author | Age | State |',
  '|---|---|---|---|---|',
  ...rows,
  '',
  '### Remediation',
  '1. Ping the author — is this still relevant?',
  '2. If stalled on review: assign a reviewer and bump priority',
  '3. If abandoned: close the PR (author can reopen if needed)',
  '4. If draft that\'s gone cold: either ship it or close',
  '',
  '---',
  `_Auto-generated by routines-hub W15 (stale-prs). Daily scan. Threshold: ≥${THRESHOLD_COUNT} stale PR. Auto-closes via G1 when empty for 3d._`,
];

try {
  const result = await ensureIssue({
    signature,
    onMatch: async (existing) => {
      const oldest = stalePrs[0];
      await commentOnIssue(
        existing.id,
        `Still present in ${TARGET_REPO} as of ${new Date().toISOString()}.\n` +
          `Current: **${stalePrs.length} stale PR${stalePrs.length === 1 ? '' : 's'}** (oldest: #${oldest.number} by @${oldest.author}, ${oldest.days}d stale).`,
      );
    },
    onNew: () => ({
      title,
      description: sections.join('\n'),
      projectKey: 'code-health',
      labelNames: ['routine'],
      priority: 3, // Medium — stalled reviews block contributors
    }),
  });
  console.log(`  ${result.action}: ${result.issue.identifier} — ${signature}`);
} catch (e) {
  console.error(`  ERROR on ${signature}: ${e.message}`);
  process.exit(1);
}
